name: Notify Slack

on: 
  push:
    branches:
      - test1

jobs:
  slack_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Slack
      run: |
        commit_message=$(git log -1 --pretty=%B)
        author_name=$(git log -1 --pretty=%an)
        curl -X POST -H 'Content-type: application/json' --data '{"text":"New scommit es on main branch:\n\nMessage: '"$commit_message"'\nAuthor: '"$author_name"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
